apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: large-node
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/large-node: "" 
  kubeletConfig:
    systemReserved: 
      cpu: 1500m
      memory: 6Gi

